### ISSUE TITLE
Roadmap: 2.0.0 and beyond

### ISSUE THREAD

**Issue by luke-biel** [frondeus/test-case#74]
This is a tracking issue for `test_case` roadmap beyond `1.x`.

Features are waiting to be implemented or are being currently implemented. `2.0.0` is coming with major codebase rewrite, thus it will be released as `rc` first to test stability and portability from `1.x` versions.

~~# 2.0.0~~

* ~~removal of `inconclusive` within description (currently deprecated)~~
* ~~removal of `hamcrest_assertions` in favor of custom solution #75~~
* ~~`#[test_case(args => with |x: T| assert!(...))]` for inline custom assertions #31~~
* ~~`#[test_case(args => using $path)]`  for custom assertion reuse #31~~
* ~~leave tested fn item in place where it's written #77~~
* ~~default `#[test_case]` with no return type matching support `Result<(), E> where E: Error` similar to `#[test]` macro #50~~

# beyond

* [ ] custom assertions can be applied to multiple `test_cases` via `#[test_case_handler($path)]` attribute #83
* [ ] override test case method names `#[test_case(args as function_name)]`, `#[test_case(args => result as function_name)]` and `#[test_case(args => result ; "description" as function_name)]` #72 
* [ ] #95
* [ ] generate test case per file in directory #78 

# research needed
* [ ] `with |val: T| -> bool {body}` is allowed without `assertion` within body
* [ ] test case name is accessible from within `test_case` block #37 
* [ ] PoC how `test_case` could look after `custom_test_frameworks` are stabilized: https://github.com/luke-biel/interrogate

**Comment by luke-biel** [comment]
Closing in favor of project
